### ISSUE TITLE
Removing intermediate things

### ISSUE THREAD

**Issue by mansuleman** [compoundjs/guides#5]
Here is the structure i propose:
1. Getting started - Crash course to CompoundJS. Create your first app, learn structure, use generators and tools.
2. Compound essentials
   Compound structure
   Routing
   Controllers
   View/layouts rendering
   View helpers
   Testing
   Deploy
3. Advanced 
   Security
   Meta-programming
   Events, Compound API
   Building extensions

**Comment by 1602** [comment]
Good stuff. Just need to replace basics with something else.

**Comment by mansuleman** [comment]
Main components

**Comment by mansuleman** [comment]
Nothing more than "Compound essentials" doesn't come into mind instead of "Intermediate things"

**Comment by 1602** [comment]
Let it be "Compound essentials". I think it's cool. Like ingredients or elements of compound. Thanks.
