### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by thyms** [compoundjs/guides#9]
All the links on guide web page are broken. http://compoundjs.github.com/guides/

**Comment by anatoliychakkaev** [comment]
They are not written yet.

**Comment by thyms** [comment]
Ok.

But it was kind of a shame when I was trying to show compoundjs to one of my colleague. Since it is public we assumed that it is ready to use but I guess we missed the text 'work in progress' on the main page.

**Comment by mansuleman** [comment]
The design is cool, i like it! I hope it will look much better when
completed, that is for sure.

2013/4/5 Deniz KALFA notifications@github.com

**Comment by 1602** [comment]
Anyways thanks for spotting. Now broken links are fixed with blank pages with invitation to contribute on guides. I think it's better than 404.
